export const OPEN_DIALOG_CONFIG = 'CHANGE_IS_REDIRECT';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const OPEN_DIALOG_TWEET = 'OPEN_DIALOG_TWEET';
export const GET_COMMENT = 'GET_COMMENT';
export const OPEN_DIALOG_FOLLOWING = "OPEN_FOLLOWING";
