export const OPEN_DIALOG_CONFIG = 'CHANGE_IS_REDIRECT';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const OPEN_DIALOG_TWEET = 'OPEN_DIALOG_TWEET';
export const GET_COMMENT = 'GET_COMMENT';
export const OPEN_DIALOG_FOLLOWING = "OPEN_FOLLOWING";
export const OPEN_DIALOG_FOLLOWER = "OPEN_FOLLOWER";
export const SAVE_TRANSACTION = "SAVE_TRANSACTION";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const DO_LOGIN = "DO_LOGIN"
export const OPEN_DIALOG_CREATE_ACCOUNT = "OPEN_LOGIN";
export const OPEN_DIALOG_SHOW_INFO = "OPEN_DIALOG_SHOW_INFO";
export const OPEN_DIALOG_POST = "OPEN_DIALOG_POST";




